REM   Script: SQL_Day_1
REM   First class of SQL.

SELECT  * 
FROM 
HR.EMPLOYEES;

SELECT * FROM HR.DEPARTMENTS;

SELECT E.*, D.* 
FROM HR.EMPLOYEES E, HR.DEPARTMENTS D 
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID;

SELECT DEPARTMENT_NAME, COUNT(DISTINCT EMPLOYEE_ID) 
    FROM( 
SELECT E.*, D.* 
FROM HR.EMPLOYEES E, HR.DEPARTMENTS D 
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID 
    ) 
GROUP BY DEPARTMENT_NAME;

SELECT DEPARTMENT_NAME, COUNT(DISTINCT EMPLOYEE_ID) 
    FROM( 
SELECT E.*, D.* 
FROM HR.EMPLOYEES E, HR.DEPARTMENTS D 
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID 
    ) 
GROUP BY DEPARTMENT_NAME 
ORDER BY 2;

SELECT DEPARTMENT_NAME, COUNT(DISTINCT EMPLOYEE_ID) 
    FROM( 
SELECT E.*, D.* 
FROM HR.EMPLOYEES E, HR.DEPARTMENTS D 
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID 
    ) 
GROUP BY DEPARTMENT_NAME 
ORDER BY 2 DESC;

SELECT DEPARTMENT_NAME, COUNT(DISTINCT EMPLOYEE_ID) AS TOTAL_NO_OF_EMPLOYEES 
    FROM( 
SELECT E.*, D.* 
FROM HR.EMPLOYEES E, HR.DEPARTMENTS D 
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID 
    ) 
GROUP BY DEPARTMENT_NAME 
ORDER BY 2 DESC;

SELECT DEPARTMENT_NAME, COUNT(DISTINCT EMPLOYEE_ID) AS "TOTAL NO OF EMPLOYEES" 
    FROM( 
SELECT E.*, D.* 
FROM HR.EMPLOYEES E, HR.DEPARTMENTS D 
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID 
    ) 
GROUP BY DEPARTMENT_NAME 
ORDER BY 2 DESC;

