// <auto-generated />
using BlazorApp.Server.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorApp.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230605095658_seeding")]
    partial class seeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("BlazorApp.Shared.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Avash"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Nitesh"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ram"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Sita"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Hari"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
